### PR TITLE
Fix tests for ruby1.8

### PR DESCRIPTION
**Pull request by madAndroid**
This addresses the test failure in #23

### CODE REVIEW

**Comment by madAndroid** [comment]
The test failure when 533130d was pushed, looks to be down to inconsistent hash ordering in ruby1.8, as far as I can tell ... and since we're using the `to_yaml` method, I'm not sure what we can do to overcome this, since we're not directly in control over the ordering. The next commit wasn't related, and the tests pass, so ¯\_(ツ)_/¯

**Comment by mkrakowitzer** [comment]
Thanks, can you squash these commits?

**Comment by madAndroid** [comment]
sure thing, done :)

**Comment by mkrakowitzer** [comment]
Thanks, Seriously why doesn’t ruby 1.8.7 just die already :/ I think lets raise an issue for the hash ordering of 1.8.7?

**Pull request merged**
