### PR TITLE
Simple support for CentOS 7 and RHEL 7

### PR DESCRIPTION
**Pull request by gdhbashton**
Howdy - JJB breaks most of the time for me since I'm using CentOS 7 - this simple conditional solves the problem using Puppet facts. Hurrah!

### CODE REVIEW

**Comment by madAndroid** [comment]
@gdhbashton - Really keen on having this change merged at some point, but it needs a rebase.. this module has seen some good traction from the community recently, would be awesome to keep up the momentum :)

**Comment by daenney** [comment]
This needs some serious work before we consider merging it. It's now touching everything from the original feature request to module syncing it with puppet-community and a bunch of other things.

It should be split across a few different PR's, or at least clear and distinct commits first.

**Comment by gdhbashton** [comment]
@madAndroid are you in a position to take this forward? We don't typically use JJB now, so there's little motivation to undertake a ton of cleanup work given other priorities. I'm minded to close this PR as I won't be able to progress it.

**Comment by madAndroid** [comment]
@gdhbashton - yep, no problem - we're still using it a lot, so it makes sense to take it over .. I do believe this particular PR should be closed in favour of #20

**Comment by daenney** [comment]
Closed it is then, in favour of #20.

**Pull request closed without merging**
